### ISSUE TITLE
stick player to bottom on snippet editor

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#57]
a minor improvement to the snippet editing page change the styles so the snippet list isn't shrunk to `50vh` (let it expand to fill page), move the `#player` element to below `.cascading-editor` stuff and then add something like

```css
#player {
    position: sticky;
    bottom: 0;
    background-color: white;
    padding: 1mm;
}
```

this sticks the player to the bottom of the viewport until the bottom of the page is reached, where it fills in where it would be normally. the `padding` is mostly there to keep it from touching the bottom of the screen, and also to give the top some edge, but at least on my screen it gives "too much" edge
